const actionTypes = {
  FETCH_SEARCH_PENDING: 'FETCH_SEARCH_PENDING',
  FETCH_SEARCH_SUCCESS: 'FETCH_SEARCH_SUCCESS',
  FETCH_SEARCH_ERROR: 'FETCH_SEARCH_ERROR',
  CLEAR_SEARCH: 'CLEAR_SEARCH',
};

export default actionTypes;
